# Generated by Django 4.0.5 on 2022-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_available_count',
            new_name='productcount',
        ),
    ]
