# Generated by Django 4.0.5 on 2022-07-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='user_image',
        ),
    ]
